package fr.minenorth.portes.network; import fr.minenorth.portes.MineNorthPortes; import fr.minenorth.portes.door.OwnerDoorData; import fr.minenorth.portes.door.OwnerDoorManager; import fr.minenorth.portes.client.ClientNetworkHandler; import net.minecraft.core.BlockPos; import net.minecraft.network.FriendlyByteBuf; import net.minecraft.server.level.ServerPlayer; import net.minecraft.server.level.ServerLevel; import net.minecraft.resources.ResourceLocation; import net.minecraftforge.api.distmarker.Dist; import net.minecraftforge.network.*; import net.minecraftforge.network.simple.SimpleChannel; import net.minecraftforge.fml.DistExecutor; import java.util.*; import java.util.function.Supplier;
public final class ModNetwork{private ModNetwork(){} private static final String PROTOCOL="1"; public static final SimpleChannel CHANNEL=NetworkRegistry.newSimpleChannel(new ResourceLocation(MineNorthPortes.MOD_ID,"network"),()->PROTOCOL,PROTOCOL::equals,PROTOCOL::equals);private static int id=0;public static void register(){CHANNEL.registerMessage(id++,DoorPanelPacket.class,DoorPanelPacket::encode,DoorPanelPacket::decode,DoorPanelPacket::handle);CHANNEL.registerMessage(id++,DoorActionPacket.class,DoorActionPacket::encode,DoorActionPacket::decode,DoorActionPacket::handle);CHANNEL.registerMessage(id++,DoorLockSyncPacket.class,DoorLockSyncPacket::encode,DoorLockSyncPacket::decode,DoorLockSyncPacket::handle);CHANNEL.registerMessage(id++,DoorInteractPacket.class,DoorInteractPacket::encode,DoorInteractPacket::decode,DoorInteractPacket::handle);}
public static void sendDoorLocks(ServerPlayer p,Collection<String> l){CHANNEL.send(PacketDistributor.PLAYER.with(()->p),new DoorLockSyncPacket(new ArrayList<>(l)));}

    /** Dernière liste de portes verrouillées envoyée à chaque joueur (hash) : on ne renvoie que si elle a changé. */
    private static final Map<UUID, Integer> LAST_LOCKS = new HashMap<>();

    public static void forgetLocks(UUID player) { LAST_LOCKS.remove(player); }

    /** Recalcule les portes verrouillées de chaque joueur et ne lui envoie la liste que si elle a changé. */
    public static void syncDoorLocks(net.minecraft.server.MinecraftServer server) {
        var data = OwnerDoorData.get(server.overworld());
        var doors = data.allDoors();
        for (ServerPlayer p : server.getPlayerList().getPlayers()) {
            var locked = new ArrayList<String>();
            for (var e : doors) {
                ServerLevel level = server.getLevel(e.getKey().dimension());
                if (level == null) continue;
                if (!OwnerDoorManager.canOpen(p, level, e.getKey().pos(), e.getValue()))
                    locked.add(e.getKey().dimension().location() + "|" + e.getKey().pos().asLong());
            }
            Collections.sort(locked);
            Integer before = LAST_LOCKS.put(p.getUUID(), locked.hashCode());
            if (before == null || before != locked.hashCode()) sendDoorLocks(p, locked);
        }
    }

public static void sendDoorPanel(ServerPlayer p,ServerLevel l,BlockPos pos,int mode,String ownerName,List<String> trusted,List<String> requests,OwnerDoorData.DoorType type,String permission,boolean temporary){var d=OwnerDoorData.get(l);var listing=d.listing(l,pos);var entry=d.get(l,pos);String house=entry==null?"":entry.houseName();String lm=listing==null?"NONE":listing.mode().name();long price=listing==null?0:listing.price();int days=listing==null?0:listing.days();String renter="";long exp=listing==null?0:listing.expiryMs();if(listing!=null&&listing.renter()!=null){ServerPlayer rp=p.server.getPlayerList().getPlayer(listing.renter());renter=rp==null?listing.renter().toString():rp.getGameProfile().getName();}long purchase=entry==null?0:entry.purchasePrice();List<String> companies=p.hasPermissions(2)?fr.minenorth.portes.door.EntrepriseCompat.companies(p.server):List.of();List<String> grades=List.of();if(fr.minenorth.portes.door.EntrepriseCompat.linked(permission)){int cid=fr.minenorth.portes.door.EntrepriseCompat.id(permission);grades=fr.minenorth.portes.door.EntrepriseCompat.grades(p.server,cid);String live=fr.minenorth.portes.door.EntrepriseCompat.name(p.server,cid);if(!live.isBlank())ownerName=live;}CHANNEL.send(PacketDistributor.PLAYER.with(()->p),new DoorPanelPacket(l.dimension().location().toString(),pos.asLong(),mode,ownerName,trusted,requests,type.name(),permission,temporary,house,lm,price,days,renter,exp,purchase,companies,grades));}
public record DoorPanelPacket(String dimension,long pos,int mode,String ownerName,List<String> trusted,List<String> requests,String type,String permission,boolean temporary,String houseName,String listingMode,long listingPrice,int listingDays,String renter,long expiryMs,long purchasePrice,List<String> companies,List<String> grades){static void encode(DoorPanelPacket p,FriendlyByteBuf b){b.writeUtf(p.dimension);b.writeLong(p.pos);b.writeVarInt(p.mode);b.writeUtf(p.ownerName);b.writeCollection(p.trusted,(x,v)->x.writeUtf(v));b.writeCollection(p.requests,(x,v)->x.writeUtf(v));b.writeUtf(p.type);b.writeUtf(p.permission);b.writeBoolean(p.temporary);b.writeUtf(p.houseName);b.writeUtf(p.listingMode);b.writeLong(p.listingPrice);b.writeVarInt(p.listingDays);b.writeUtf(p.renter);b.writeLong(p.expiryMs);b.writeLong(p.purchasePrice);b.writeCollection(p.companies,(x,v)->x.writeUtf(v));b.writeCollection(p.grades,(x,v)->x.writeUtf(v));}static DoorPanelPacket decode(FriendlyByteBuf b){return new DoorPanelPacket(b.readUtf(),b.readLong(),b.readVarInt(),b.readUtf(),b.readList(FriendlyByteBuf::readUtf),b.readList(FriendlyByteBuf::readUtf),b.readUtf(),b.readUtf(),b.readBoolean(),b.readUtf(),b.readUtf(),b.readLong(),b.readVarInt(),b.readUtf(),b.readLong(),b.readLong(),b.readList(FriendlyByteBuf::readUtf),b.readList(FriendlyByteBuf::readUtf));}static void handle(DoorPanelPacket p,Supplier<NetworkEvent.Context> c){c.get().enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->ClientNetworkHandler.openDoorPanel(p)));c.get().setPacketHandled(true);}}
public record DoorActionPacket(int action,String text,boolean flag,String extra){static void encode(DoorActionPacket p,FriendlyByteBuf b){b.writeVarInt(p.action);b.writeUtf(p.text);b.writeBoolean(p.flag);b.writeUtf(p.extra);}static DoorActionPacket decode(FriendlyByteBuf b){return new DoorActionPacket(b.readVarInt(),b.readUtf(),b.readBoolean(),b.readUtf());}static void handle(DoorActionPacket p,Supplier<NetworkEvent.Context> c){c.get().enqueueWork(()->{ServerPlayer sp=c.get().getSender();if(sp!=null)OwnerDoorManager.handleAction(sp,p.action(),p.text(),p.flag(),p.extra());});c.get().setPacketHandled(true);}}
public record DoorLockSyncPacket(List<String> locked){static void encode(DoorLockSyncPacket p,FriendlyByteBuf b){b.writeCollection(p.locked,(x,v)->x.writeUtf(v));}static DoorLockSyncPacket decode(FriendlyByteBuf b){return new DoorLockSyncPacket(b.readList(FriendlyByteBuf::readUtf));}static void handle(DoorLockSyncPacket p,Supplier<NetworkEvent.Context> c){c.get().enqueueWork(()->DistExecutor.unsafeRunWhenOn(Dist.CLIENT,()->()->ClientNetworkHandler.syncLocks(p.locked)));c.get().setPacketHandled(true);}}
public record DoorInteractPacket(long pos,boolean sneaking){static void encode(DoorInteractPacket p,FriendlyByteBuf b){b.writeLong(p.pos);b.writeBoolean(p.sneaking);}static DoorInteractPacket decode(FriendlyByteBuf b){return new DoorInteractPacket(b.readLong(),b.readBoolean());}static void handle(DoorInteractPacket p,Supplier<NetworkEvent.Context> c){c.get().enqueueWork(()->{ServerPlayer sp=c.get().getSender();if(sp!=null)OwnerDoorManager.handleClientInteract(sp,BlockPos.of(p.pos),p.sneaking);});c.get().setPacketHandled(true);}}}
